id: I09A9F0FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:31:41+00:00'
last_modified: '2022-06-07T12:29:57.692751+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25350
  title: བོད་གངས་ཅན་གྱི་སྒྲ་རིག་པའི་བསྟན་བཅོས་ལེ་ཚན་འགའ་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '9432':
      image_group_id: I1KG25352
      title: ''
      total_pages: 84
      order: 1
      base_file: 9432.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
