id: P000626
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25350
  title: བོད་གངས་ཅན་གྱི་སྒྲ་རིག་པའི་བསྟན་བཅོས་ལེ་ཚན་འགའ་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    0a58ee478dc849afa491adcc6aa78bc7:
      image_group_id: I1KG25352
      title: ''
      volume_number: 1
      total_pages: 84
